### ISSUE TITLE
Multisig connect

### ISSUE THREAD

**Issue by trongcauhcmus** [BitGo/eth-multisig-v2#6]
i saw many contract have the same opcode for example at the address 0xD4F5bf184BeBFD53AC276ec6E091d051D0ed459E. it link to bitgo multisig wallet, i don't know how to make a transaction right on the remix. Can you guide me? i want to make a transaction on testnet to catch the event and detect deposit to my wallet. thanks

**Comment by acinmavi** [comment]
I don't really understand your question , but as far as I know , there are some steps to make transaction to multisig address :
1.You have to deploy WalletSimple.sol : 
  + Go to https://remix.ethereum.org , upload bitgo contract folder to this
  + Select right compiler (0.4.18+commit.9cf6e910.Emscripten.clang)
  + Compile it ( in tab Compile)
  + Go to tab run , choose WalletSimple , input allowedSigners (exam : ["0xaaae94866cf1dfc8f88fac33f907baad77a133b6","0xf7610c091d01f315515507aee14b16ec6cb12b48","0x506702c8e9f55ee96e005b0ee33f2348e82aee6e"])
   + Choose environment and deploy ( if you use Ropsten , I recommend use Inject web3 , you need to install MetaMask on your browser extension)
After finish deploy , you got contract address , this is "multisig" address you need. After that , you could deposit to or withdraw from this contract address.
With deposit , this is easy , you need to go to your wallet and transfer some coin to contract address , then check it via etherscan or some block exploxer site.
With withdraw , this is more complicate. If you need to more detail on this part , please question , I will make detail explaintion.

**Comment by LordomusPrime** [comment]
Hi @acinmavi
I've been trying out the contract and have recently deployed one on Ropsten Testnet via remix. I've been able to deposit and check my balances accordingly. But I'm having trouble withdrawing and transferring Eth using SendMultiSig. Would it be possible for you post instructions on how to properly use the function? Thanks

**Comment by Wangmmx** [comment]
> Hi @acinmavi
> I've been trying out the contract and have recently deployed one on Ropsten Testnet via remix. I've been able to deposit and check my balances accordingly. But I'm having trouble withdrawing and transferring Eth using SendMultiSig. Would it be possible for you post instructions on how to properly use the function? Thanks

I got the same problem when using SendMultiSig

**Comment by trongcauhcmus** [comment]
bitgo multisig wallet use 2/3 signature.
the first signature will be create offline by the first private key. with the argument:
```     
address toAddress
uint value
address tokenContractAddress
uint expireTime
uint sequenceId
```
after that, the 2nd private key use to push transaction by calling sendMultiSig
the signature attach together with the argument above for smart contract verify

**Comment by affankhan43** [comment]
Hi @Wangmmx  @trongcauhcmus !
How can i get data and signture parameters for  sendmutisig

**Comment by acinmavi** [comment]
I leave this topic for long time ago after making app to deploy smart contract and deposit, withdraw using bitgo multisig wallet (with a little modify) in Java language.
"SendMultiSig" function used for withdraw , and these are some parameters when using this function
`function sendMultiSig(
      address toAddress,       >>> it is destination address
      uint value,                      >>> it is value to withdraw
      bytes data,       >>> it is additional data , if empty , set it 0x
      uint expireTime,     >>> expire time of this tx , in long value
      uint sequenceId,    >>> this is return value from getNextSequenceId function
      bytes signature      >>> this is combination of keccak256(toAddress, value, data, expire, sequenceId)
`
With original WalletSimple.sol , I could not get data of signature , although I tried many time to impelment keccak algorithm , the result still NG. Somehow , my friend using Go language has their example works. I didn't know where I was wrong.
After investigating and have no result , I decide to modify WalletSimple.sol to get signature value , because I saw on sendMultiSig function have :
var operationHash = keccak256("ETHER", toAddress, value, data, expireTime, sequenceId);
So I modify this wallet and added function :
 `function getShaEther(
     address toAddress,  
     uint value,  
     bytes data,  
     uint expireTime,  
     uint sequenceId
     ) public onlySigner view returns(bytes32) {
     return keccak256("ETHER", toAddress, value, data, expireTime, sequenceId);
    }
`
So I could redeploy again smart contract , and when call sendMultiSig , I get signature by calling :
getShaEther(toAddress, value, data, expire, sequenceId);
And guess what , it worked.  I attach sol file here , if it could help someone.
Java code , I use web3j to code. If anyone want to see it , I paste here also :
`public String sendMultisigTx(String contractAddress, String pass1, String pass2, long salt, String toAddress, BigDecimal amount, BigInteger nonce) throws Exception {
        val key1 = Coins.generateHDKey(pass1, salt);
        val key2 = Coins.generateHDKey(pass2, salt);
        val credentials1 = Credentials.create(key1.getPrivateKeyAsHex());
        val credentials2 = Credentials.create(key2.getPrivateKeyAsHex());

        val contractGasProvider = new VTradeGasProvider(web3j);
        val transactionManager = new VTradeTransacitonManager(web3j, credentials1, (byte) this.gethId, new NoOpProcessor(web3j));
        transactionManager.setNonce(nonce);
        val contract = WalletSimple.load(contractAddress, web3j, transactionManager, contractGasProvider);

        val data = Strings.EMPTY.getBytes();
        val sequenceId = contract.getNextSequenceId().send();
        val expire = BigInteger.valueOf(DateTimes.addHours(DateTimes.currentTimeMillis(), 1));
        val value = Coins.Ethereums.convertEthToWei(amount);
        val keccak256 = contract.getShaEther(toAddress, value, data, expire, sequenceId).send();
        val signatureData = Sign.signMessage(keccak256, credentials2.getEcKeyPair(), false);
        val signature = signatureEncode(signatureData);
        LOGGER.info("start to send multisig tx from {} , to {} , amount {} ", contractAddress, toAddress, amount);
        val receipt = contract.sendMultiSig(toAddress, value, Numeric.hexStringToByteArray(Coins.Ethereums.addPrefix(Hex.toHexString(data))), expire, sequenceId, Numeric.hexStringToByteArray(Coins.Ethereums.addPrefix(Hex.toHexString(signature)))).send();
        return receipt.getTransactionHash();
    }`
[WalletSimple.zip](https://github.com/BitGo/eth-multisig-v2/files/3176796/WalletSimple.zip)

**Comment by affankhan43** [comment]
@acinmavi  Thanks man

**Comment by codelzl** [comment]
How do i get the parameters ？
